### ISSUE TITLE
install-to-internal not working on Samsung Chromebook 4 | Intel Gemini lake

### ISSUE THREAD

**Issue by kylar-b** [eupnea-linux/postinstall-scripts#2]
Running `install-to-internal` returns:
```
 Traceback (most recent call last):
  File "/usr/local/bin/install-to-internal", line 190, in <module>
    partition_and_flash()
  File "/usr/local/bin/install-to-internal", line 62, in partition_and_flash
    bash(f"cgpt add -i 1 -t kernel -S 1 -T 5 -P 15 {internal_name}")  # depthcharge flags
  File "/usr/local/bin/functions.py", line 119, in bash
    output = subprocess.check_output(command, shell=True, text=True).strip()
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cgpt add -i 1 -t kernel -S 1 -T 5 -P 15 /dev/mmcblk0' returned non-zero exit status 127.
```

**Comment by Apacelus** [comment]
The scripts are broken atm, please dont run anything

**Comment by Apacelus** [comment]
Alright, I made the necessary changes. Make a new build and try again
